config/routes.rb
Rails.application.routes.draw do

  root 'languages#index'

  resources :languages, only: [:index, :show, :new, :create, :edit, :update ]

  delete '/languages/:id/delete' => 'languages#destroy', as: 'delete'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/language.rb
class Language < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_action :set_language, only: [:show, :edit, :update, :destroy]

  def index
    @languages = Language.all
  end

  def show
  end

  def new
    @language = Language.new
  end

  def create
    @language = Language.new(language_params)
    if @language.save
      redirect_to @language, notice: 'Language was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @language.update(language_params)
      redirect_to @language, notice: 'Language was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @language.destroy
    redirect_to languages, notice: 'Language was successfully destroyed.'
  end

  private

  def set_language
    @language = Language.find(params[:id])
  end

  def language_params
    params.require(:language).permit(:title, :description, :link)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/language_helper.rb
module LanguageHelper
end

app/views/languages/edit.html.erb
<section class="language-edit container mt-5">
  <header>
    <h2>Edit <%= @language.title %></h2>
  </header>

  <%= form_with(model: @language, local: true) do |form| %>
    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_area :description, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :link %>
      <%= form.text_field :link, class: "form-control" %>
    </div>

    <div class="actions">
      <%= form.submit "Update Language", class: "btn btn-primary" %>
      <%= link_to "Cancel", root_path, class: "btn btn-secondary" %>
    </div>
  <% end %>
</section>

app/views/languages/index.html.erb
<section class="language-index container mt-5">
  <header>
    <h1>Programming Languages</h1>
  </header>


  <div class="mt-3">
    <%= link_to 'New', new_language_path, class: "btn btn-primary" %>
  </div>

  <table class="table">
    <thead>
        <tr>
          <th scope="col">Title</th>
          <th scope="col">Description</th>
          <th scope="col">View</th>
          <th scope="col">Edit</th>
          <th scope="col">Delete</th>
        </tr>
    </thead>
    <tbody>
        <% @languages.each do |language| %>
          <tr>
            <td><%= language.title %></td>
            <td><%= language.description %></td>
            <td><%= link_to 'View', language, class: "btn btn-success btn-sm" %></td>
            <td><%= link_to 'Edit', edit_language_path(language), class: "btn btn-primary btn-sm" %></td>
            <td><%= link_to 'Delete', language, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>

            </td>
          </tr>
        <% end %>
    </tbody>
  </table>
</section>

app/views/languages/new.html.erb
<section class="language-new container mt-5">
  <header>
    <h2>Create a New Programming Language</h2>
  </header>

  <%= form_with(model: @language, local: true) do |form| %>
    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_area :description, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :link %>
      <%= form.text_field :link, class: "form-control" %>
    </div>

    <div class="actions">
      <%= form.submit "Create Language", class: "btn btn-primary" %>
      <%= link_to "Cancel", languages_path, class: "btn btn-secondary" %>
    </div>
  <% end %>
</section>

app/views/languages/show.html.erb
<section class="language-show container mt-5">
  <header>
    <h1><%= @language.title %></h1>
  </header>

  <div class="row">
    <div class="col-md-9">
      <h3>Description</h3>
      <p><%= @language.description %></p>
      <h3>Official Link</h3>
      <p><a href="<%= @language.link %>"><%= @language.link %></a></p>
    </div>
  </div>

  <div class="mt-4">
    <%= link_to 'Edit', edit_language_path(@language), class: "btn btn-primary" %>
    <%= link_to 'Back', languages_path, class: "btn btn-secondary" %>
    <%= link_to 'Delete', @language, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProgrammingLanguagesApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>